[package]
name = "threads-on-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qlrl = { path = "../../qlrl" }
bus = "2.3.0"
env_logger = "0.9.1"
log = "0.4.17"
ctrlc = "3.2.3"
